config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :tickets
  resources :staff, :only => [:index]
  resources :client, :only => [:index]
  resources :comments, :only => [:create]
  root 'home#index'
  get 'news/index'
  
  get 'contacts/index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	after_create :set_status
	
	#associations
	has_many :comment, :as => :commentable
	has_one :attachment, as: :attachable
	belongs_to :department
	belongs_to :priority
	belongs_to :status
	belongs_to :user

	accepts_nested_attributes_for :attachment, allow_destroy: true

	#validations
    validates :department, :presence => { :message => "Please select any department" }
    validates :priority, :presence => { :message => "Please select priority" }
    validates :subject, :presence => { :message => "subject cannot be blank" }
    validates :message, :presence => { :message => "message cannot be blank" }

	#scopes
	scope :active, ->{ where(active: true) }
  scope :inactive, ->{ where(active: false) }
	scope :pending, ->{ joins(:status).where('statuses.name =?', 'pending') }
	scope :waiting, ->{ joins(:status).where('statuses.name =?', 'awaiting for users reply') }
	scope :closed, ->{ joins(:status).where('statuses.name =?', 'closed') }

    def set_status
        @status = Status.find_by(name: "pending")
        self.update_attributes(status_id: @status.id)
    end

    def update_status(tid,ticket)
    	if (ticket.status.name == "pending") || (ticket.status.name == "awaiting for users reply")
      		@sid = Status.find_by_name("closed")
      		ticket.update_attributes(:status_id => @sid.id)
    	elsif (ticket.status.name == "closed")
      		@sid = Status.find_by_name("pending")
      		ticket.update_attributes(:status_id => @sid.id)
    	end
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]

	def index
		@tickets = Ticket.all
    @comment = Comment.all
	end


	def new
		@tickets = Ticket.new
    @dept = Department.all
    @priority = Priority.all
	end

	def create
		@tickets = Ticket.new(ticket_params)
    @tickets.user_id = current_user.id      
    respond_to do |format|
    	if @tickets.save
       	format.html { redirect_to @tickets, notice: 'Ticket was successfully created.' }
      else
       	format.html { render :new }
      end
    end
	end
  
  def show
    @comments = Comment.where(:ticket_id => params[:id])
  end


	def update
    @tid = params[:id]
    @ticket = Ticket.find_by_id(@tid)
    @ticket.update_status(@tid,@ticket)
    respond_to do |format|
      format.html { redirect_to @tickets, notice: 'Ticket was successfully updated.' }   
    end
  end

 	private
    def set_ticket
     	@tickets = Ticket.find(params[:id])
    end

    def ticket_params
    	params.require(:ticket).permit(:subject, :message, :active, :department_id, :priority_id, :status_id, attachment_attributes: [:attachment]  )
    end
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/tickets/edit.html.erb
<section class="well well-small mePadd">
                <h2 class="meFont" style="padding-bottom:30px;"><span class="icon-comment meMarg"></span> Edit profile</h2>
                    <div class="">
<%= form_for((@tickets), html: {class: "form-actions form-horizontal"}) do |f| %>
<%= devise_error_messages! %>


<div class="control-group">
<label class="control-label" for="">Subject:</label>
<div class="controls">
  <%= f.text_field :subject,value: current_ticket.subject, class: "input-block-level" %>
</div>
</div>
  
<div class="control-group">
<label class="control-label" for="">Message:</label>
<div class="controls">
  <%= f.text_area :message,value: current_ticket.message, class: "input-block-level" %>
</div>
</div>



<div class="control-group">
<label class="control-label" for="">Department:</label>
<div class="controls">
<select id="ticket_department_id" name="ticket[department_id]">
<option value="">Select department</option>
<% @dept.each do |a| %>
<option value= "<% a.id %>" > <%= a.name %> </option>
<% end %>
</select>
</div>
</div>

<div class="control-group">
<label class="control-label" for="">Priority:</label>
<div class="controls">
<select id="ticket_priority_id" name="ticket[priority_id]">
<option value="">Select Priority</option>
<% @priority.each do |b| %>
<option value= "<% b.id %>" > <%= b.name %> </option>
<% end %>
</select>
</div>
</div>


<div class="control-group pull-right">
<div class="controls">
<button type="submit" class="btn" name="editUser">Update</button>
</div>
</div>



<% end %>
</div>
</section><!--Edit ticket Ends-->

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th>subject</th>
      <th>message</th>
      <th>department</th>
      <th>priority</th>
      <th>status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.subject %></td>
        <td><%= ticket.message %></td>
        <td><%= ticket.department_id %></td>
        <td><%= ticket.priority_id %></td>
        <td><%= ticket.status_id %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tickets/new.html.erb
<section class="well well-small mePadd">
                <h2 class="meFont" style="padding-bottom:30px;"><span class="icon-comment meMarg"></span> New Ticket</h2>
                    <div class="">
<%= form_for((@tickets), html: {class: "form-actions form-horizontal"}) do |f| %>
<% if @tickets.errors.any? %>
<%= pluralize(@tickets.errors.count, "error") %>
<ul>
<% @tickets.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
<% end %>
</ul>

<div class="control-group">
<label class="control-label" for="">Subject:</label>
<div class="controls">
  <%= f.text_field :subject, autofocus: true, class: "input-block-level" %>
</div>
</div>
  
<div class="control-group">
<label class="control-label" for="">Message:</label>
<div class="controls">

  <%= f.text_area :message, class: "input-block-level" %>
</div>
</div>



<div class="control-group">
<label class="control-label" for="">Department:</label>
<div class="controls">
<%=f.select :department_id, options_for_select(@dept.map{ |c| [c.name, c.id]}) %>
</div>
</div>

<div class="control-group">
<label class="control-label" for="">Priority:</label>
<div class="controls">
<%=f.select :priority_id, options_for_select(@priority.map{ |d| [d.name, d.id]}) %>
</div>
</div>

<div class="control-group">
<label class="control-label" for="">Attachment:</label>
<div class="controls">
<%= f.fields_for :attachment, (Attachment.new) do |attachment_form| %>
     
<%= attachment_form.file_field :attachment %>

<%end%>
</div>
</div>



<div class="control-group pull-right">
<div class="controls">
<%= f.submit %>
</div>
</div>



<% end %>
</div>
</section><!--Edit user profile Ends-->

app/views/tickets/show.html.erb
<article class="container" style="margin-top:-18px;">
	<section class="well well-small mePadd"><h2 class="meFont" style="padding-bottom:30px;"><span class="icon-search meMarg"></span> <%=@tickets.try(:user).try(:user_name)%><br/> Subject:<%=@tickets.subject.upcase%></h2>
       	<div class="resTable2">
           	<h4 class="alert alert-heading" style="font-style: italic;">Date modified: <span class="spnPadding"><%= @tickets.updated_at.strftime(" %d/%m/%Y") %>  </span> 
           	Time modified: <span class="spnPadding"><%= @tickets.updated_at.strftime("%H:%M") %>  </span>
            
           
           	<% if current_user_role.name == "client" %>
           		<% if @tickets.status.name == "closed" %>
           			<span class="floatR">
        	    		<%= link_to "Reopen", ticket_path, class: 'btn btn-danger',method: :put %>
 	        		</span>
           		<% else %>
            		<span class="floatR">
        	    		<button class="btn btn-success" type="button" data-toggle="modal" data-target="#myModal"> Reply</button>
    	            	<%= link_to "Close", ticket_path, class: 'btn btn-danger',method: :put %>
	 	        	</span>
            	<% end %>

            <% elsif current_user_role.name == "staff" %>

            	<% if @tickets.status.name == "closed" %>
           		
           		<% else %>
            		<span class="floatR">
        	    		<button class="btn btn-success" type="button" data-toggle="modal" data-target="#myModal"> Reply</button>
	 	        	</span>
            	<% end %>
            <% end %>

            </h4>


			                <div class="myTable4">
			                    <table class="table table-striped table-condensed">
			                      <tbody><tr class="tableFont">
			                        <td>ID</td>
			                        <td>Department</td>
			                        <td>Status</td>
			                        <td>Priority</td>
			                      </tr>
			                      <tr class="tableFont2">
			                        <td><%=@tickets.id%></td>
			                        <td>
			                        	<%=@tickets.department.name%>
			                        </td>
			                        <td> <%=@tickets.status.name%></td>
			                        <td><%=@tickets.priority.name%></td>
			                      </tr>
			                    </tbody></table>
			                </div>
			                <h4 class="alert " style="font-style: italic;">Description: <span class="spnPadding"><%= @tickets.message %></span></h4>
			                <% if @tickets.attachment.blank? %>
			                <% else %>
			                <%= link_to "Click here to view the document", @tickets.attachment.attachment.url(:original, false) %>
			            	<%end%>
			            </div>
			     
			            <hr> <div class=""><h2 class="meFont" style="padding-bottom:30px;"> Conversation:</h2>
			            <% @comments.each do |c|%>
			            <% @user_id = c.user_id %>   
        					<%@user = User.find_by_id(@user_id)%>
        					<%@role_name = @user.role.name %>
			            <li class="alert alert-user meUs">
								
								<%= image_tag(@user.attachment ? @user.attachment.attachment : "user.png",class: "img-circle", size: "50x50") %>
								
								
								<span class="tableFont"> <%= @role_name.upcase%>:</span>
								<span class="tableFont2" style="background-color:transparent;"><%= @user.first_name%></span>
								<h6 class="fk">Posted on: <span><%= c.created_at.strftime(" %d/%m/%Y, %H:%M") %></span></h6>
								<div class="alert alert-user meUser">
								   <%= c.comment%>.</div>
								   <% if c.attachment.blank? %>

			                <% else %>
			                <%= link_to "Click here to view the document", c.attachment.attachment.url(:original, false) %>
			            	<%end%>
                     		  </li>
                    <%end%>



						 </div>
          			 </section>
				 <div class="modal hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"><!--Modal Starts-->
		        	<div class="modal-header">
		            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		            <h3 id="myModalLabel">Send message</h3>
		            </div>
		            <%= form_for(:comment, url: comments_path) do |f| %>
		            <div class="modal-body">
		            
		            <%= f.text_area :comment, class: "modalTextarea" %>
		            </div>

		            <div class="modal-footer">
		            <%= f.fields_for :attachment_attributes, Attachment.new do |attachment_form| %>
    				<%= attachment_form.file_field :attachment %>
    				<%end%>
		            <%= f.hidden_field :ticket_id, :value => @tickets.id%>
		            <button class="btn btn-success" type="submit" ><span class="icon-arrow-right icon-white"></span> Send</button>
		            <button class="btn" data-dismiss="modal" aria-hidden="true"><span class="icon-thumbs-down"></span> Cancel</button>
		            </div>
		            <%end%>
       			 </div><!--Modal Ends--> <!--Details Ends-->
			</article>