config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :tickets
  resources :staff, :only => [:index]
  resources :client, :only => [:index]
  resources :comments, :only => [:create]
  root 'home#index'
  get 'news/index'
  
  get 'contacts/index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	after_create :set_status
	
	#associations
	has_many :comment, :as => :commentable
	has_one :attachment, as: :attachable
	belongs_to :department
	belongs_to :priority
	belongs_to :status
	belongs_to :user

	accepts_nested_attributes_for :attachment, allow_destroy: true

	#validations
    validates :department, :presence => { :message => "Please select any department" }
    validates :priority, :presence => { :message => "Please select priority" }
    validates :subject, :presence => { :message => "subject cannot be blank" }
    validates :message, :presence => { :message => "message cannot be blank" }

	#scopes
	scope :active, ->{ where(active: true) }
  scope :inactive, ->{ where(active: false) }
	scope :pending, ->{ joins(:status).where('statuses.name =?', 'pending') }
	scope :waiting, ->{ joins(:status).where('statuses.name =?', 'awaiting for users reply') }
	scope :closed, ->{ joins(:status).where('statuses.name =?', 'closed') }

    def set_status
        @status = Status.find_by(name: "pending")
        self.update_attributes(status_id: @status.id)
    end

    def update_status(tid,ticket)
    	if (ticket.status.name == "pending") || (ticket.status.name == "awaiting for users reply")
      		@sid = Status.find_by_name("closed")
      		ticket.update_attributes(:status_id => @sid.id)
    	elsif (ticket.status.name == "closed")
      		@sid = Status.find_by_name("pending")
      		ticket.update_attributes(:status_id => @sid.id)
    	end
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]

	def index
		@tickets = Ticket.all
    @comment = Comment.all
	end


	def new
		@tickets = Ticket.new
    @dept = Department.all
    @priority = Priority.all
	end

	def create
		@tickets = Ticket.new(ticket_params)
    @tickets.user_id = current_user.id      
    respond_to do |format|
    	if @tickets.save
       	format.html { redirect_to @tickets, notice: 'Ticket was successfully created.' }
      else
       	format.html { render :new }
      end
    end
	end
  
  def show
    @comments = Comment.where(:ticket_id => params[:id])
  end


	def update
    @tid = params[:id]
    @ticket = Ticket.find_by_id(@tid)
    @ticket.update_status(@tid,@ticket)
    respond_to do |format|
      format.html { redirect_to @tickets, notice: 'Ticket was successfully updated.' }   
    end
  end

 	private
    def set_ticket
     	@tickets = Ticket.find(params[:id])
    end

    def ticket_params
    	params.require(:ticket).permit(:subject, :message, :active, :department_id, :priority_id, :status_id, attachment_attributes: [:attachment]  )
    end
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/admin/tickets/show.html.erb
<br/>
<br/>
<article class="container" style="margin-top:-18px;">
	<section class="well well-small mePadd">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= link_to "Back",admin_tickets_path,class:"tableFont"%>
<br/>
<br/>
<div class="myTable4">
			                    <table class="table table-striped table-condensed">
			                      <tbody><tr class="tableFont">
			                        <td>ID</td>
			                        <td>Subject</td>
			                        <td>Message</td>
			                        <td>Department</td>
			                        <td>Status</td>
			                        <td>Priority</td>
			                      </tr>
			                      <tr class="tableFont2">
			                        <td><%=@ticket.id%></td>
			                      <td><%= @ticket.subject%></td>
			                     <td><%= @ticket.message%></td>

			                        <td>
			                        	<%=@ticket.department.name%>
			                        </td>
			                        <td> <%=@ticket.status.name%></td>
			                        <td><%=@ticket.priority.name%></td>
			                      </tr>
			                    </tbody></table>
			                </div>

<br/>
<br/>
<br/>
<h3>Comments:</h3>
<br/>
<br/>
<div class="myTable4">
<table class="table table-striped table-condensed">
  <thead>
    <tr class="tableFont">
      <th>Name</th>
      <th>Comment</th>
      <th>Created_at</th>
      <th>Attachments</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr class="tableFont2">
       <td><%= comment.user.user_name%></td>
	<td><%= comment.comment%></td>
	<td><%= comment.created_at.strftime(" %d/%m/%Y")%></td>
	<% if comment.attachment.blank? %>

			                <% else %>
			                <td><%= link_to "Click here to view the document", comment.attachment.attachment.url(:original, false) %></td>
			            	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>
</article>