config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :tickets
  resources :staff, :only => [:index]
  resources :client, :only => [:index]
  resources :comments, :only => [:create]
  root 'home#index'
  get 'news/index'
  
  get 'contacts/index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :attachable, polymorphic: true

has_attached_file :attachment, 
		:styles => { :medium => "300x300>", :thumb => "100x100>", :mini => "50x50>" }
		# :default_url => "/images/Dummy.jpg", 
		# :s3_permissions => :public_read,
		# :storage => :s3,
		# :s3_credentials => YAML.load_file("config/aws.yml")

	validates_attachment :attachment, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	
  	has_one :attachment, as: :attachable
  	belongs_to :commentable, :polymorphic => true
    belongs_to :user
	accepts_nested_attributes_for :attachment, allow_destroy: true

	def update_status(comment)
 		@id = comment.ticket_id
    	@tc = Ticket.find_by_id(@id)
    	if @tc.status.name != "closed"
        	@sid = Status.find_by_name("awaiting for users reply")
        	@tc.update_attributes(:status_id => @sid.id)
    	end
	end
end

app/models/department.rb
class Department < ActiveRecord::Base
	
	#associations
	has_many :users
	has_many :tickets
	

	#validations
	validates :name, :presence => { :message => "name cannot be blank" }
	validates :description, :presence => { :message => "description cannot be blank" }

	#scopes
	scope :active, ->{ where(active: true) }
    scope :inactive, ->{ where(active: false) }


end

app/models/priority.rb
class Priority < ActiveRecord::Base
	has_many :tickets
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/status.rb
class Status < ActiveRecord::Base
	
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	after_create :set_status
	
	#associations
	has_many :comment, :as => :commentable
	has_one :attachment, as: :attachable
	belongs_to :department
	belongs_to :priority
	belongs_to :status
	belongs_to :user

	accepts_nested_attributes_for :attachment, allow_destroy: true

	#validations
    validates :department, :presence => { :message => "Please select any department" }
    validates :priority, :presence => { :message => "Please select priority" }
    validates :subject, :presence => { :message => "subject cannot be blank" }
    validates :message, :presence => { :message => "message cannot be blank" }

	#scopes
	scope :active, ->{ where(active: true) }
  scope :inactive, ->{ where(active: false) }
	scope :pending, ->{ joins(:status).where('statuses.name =?', 'pending') }
	scope :waiting, ->{ joins(:status).where('statuses.name =?', 'awaiting for users reply') }
	scope :closed, ->{ joins(:status).where('statuses.name =?', 'closed') }

    def set_status
        @status = Status.find_by(name: "pending")
        self.update_attributes(status_id: @status.id)
    end

    def update_status(tid,ticket)
    	if (ticket.status.name == "pending") || (ticket.status.name == "awaiting for users reply")
      		@sid = Status.find_by_name("closed")
      		ticket.update_attributes(:status_id => @sid.id)
    	elsif (ticket.status.name == "closed")
      		@sid = Status.find_by_name("pending")
      		ticket.update_attributes(:status_id => @sid.id)
    	end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    TEMP_EMAIL_PREFIX = 'change@me'
    TEMP_EMAIL_REGEX = /\Achange@me/
  
    devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
    attr_accessor :client
   
    
    #accociations
    has_one :attachment, as: :attachable
    has_many :comment, :as => :commentable
	has_many :tickets
    belongs_to :department
    belongs_to :role

    accepts_nested_attributes_for :attachment, allow_destroy: true
    
    #validations
    validates :first_name, :presence => { :message => "cannot be blank" }
    validates :mobile_no, :presence => { :message => "cannot be blank" }
    validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

    #scopes																																																																																																																																																																																												
    scope :active, ->{ where(active: true) }
    scope :inactive, ->{ where(active: false) }
    scope :client, ->{ joins(:role).where('roles.name =?', 'client') }
    scope :staff, ->{ joins(:role).where('roles.name =?', 'staff') }
    scope :active_staff, ->{ active.staff }
    scope :active_client, ->{ active.client }
    scope :inactive_staff, ->{ inactive.staff }
    scope :inactive_client, ->{ inactive.client }

    def user_name
        (first_name + " " + last_name).upcase
    end
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
before_action :authenticate_user! 
protect_from_forgery with: :null_session
	
  def index
    @tickets = Ticket.where(user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController




	before_action :navication, only: :index
	def index
	end

	private

	def navication
		if (user_signed_in?) and (current_user_role.name == "staff")
  			redirect_to staff_index_path
        elsif (user_signed_in?) and (current_user_role.name == "client")
       	 	redirect_to client_index_path
		end 
	end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
	before_action :authenticate_user!

	def index
    status = params[:status_name] || "assigned_tickets"
    @t = []
    @ticket = Ticket.where("department_id =?", current_user.department_id)
    @ticket.each do |s|
      if status == s.status.name
        @t << s
      elsif status == "assigned_tickets"
        @t << s
      end
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]

	def index
		@tickets = Ticket.all
    @comment = Comment.all
	end


	def new
		@tickets = Ticket.new
    @dept = Department.all
    @priority = Priority.all
	end

	def create
		@tickets = Ticket.new(ticket_params)
    @tickets.user_id = current_user.id      
    respond_to do |format|
    	if @tickets.save
       	format.html { redirect_to @tickets, notice: 'Ticket was successfully created.' }
      else
       	format.html { render :new }
      end
    end
	end
  
  def show
    @comments = Comment.where(:ticket_id => params[:id])
  end


	def update
    @tid = params[:id]
    @ticket = Ticket.find_by_id(@tid)
    @ticket.update_status(@tid,@ticket)
    respond_to do |format|
      format.html { redirect_to @tickets, notice: 'Ticket was successfully updated.' }   
    end
  end

 	private
    def set_ticket
     	@tickets = Ticket.find(params[:id])
    end

    def ticket_params
    	params.require(:ticket).permit(:subject, :message, :active, :department_id, :priority_id, :status_id, attachment_attributes: [:attachment]  )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/ticket_helper.rb
module TicketHelper
end

app/views/layouts/_client_header.html.erb
<div class="navbar navbar-inverse" style="position: static;">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".subnav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/client">SupportStack</a>
     
        <div class="nav-collapse subnav-collapse">
          <ul class="nav">
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle " data-toggle="dropdown">Tickets <b class="caret"></b></a>
              <ul class="dropdown-menu">
              <li class="divider"></li>
              <li><a href="/client">My tickets: <span class="myBadge"><%=client_ticket_count%></span></a></li>
              <li class="divider"></li>               
          </ul>
            </li>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Create A New Ticket <b class="caret"></b></a>
            <ul class="dropdown-menu paddingLR">
              <li class="myForm pull-left">
              <p></p>
              


              
              <%= form_for(:ticket, url: tickets_path, html: {class: "form-inline navbar-search"}) do |f| %>  
                <div class="control-group paddingLR">
                  <label class="control-label" for="inputPassword">Subject</label>
                  <div class="">
                    <%= f.text_field :subject, autofocus: true, class: "input-block-level" %>
                  </div>   
                </div>
                
                <div class="control-group paddingLR">
                  <label class="control-label" for="inputPassword">Message</label>
                  <div class="">
                  <%= f.text_area :message, class: "input-block-level" %>  
                  </div>
                </div>
                                        
                <div class="control-group paddingLR">
                  <label class="control-label" for="inputPassword">Department</label>
                  <div class="">
                    <% @dept = Department.all %>
                    <%=f.select :department_id, options_for_select(@dept.map{ |c| [c.name, c.id]}) %>
                  </div>
                </div>
                                     
                <div class="control-group paddingLR">
                  <label class="control-label" for="inputPassword">Priority</label>
                  <div class="">
                    <% @priority = Priority.all %>
                    <%=f.select :priority_id, options_for_select(@priority.map{ |d| [d.name, d.id]}) %>
                  </div>
                </div>

                 <div class="control-group paddingLR">
                  <label class="control-label" for="inputPassword">Attachment</label>
                  <div class="">
                    <%= f.fields_for :attachment_attributes, Attachment.new do |attachment_form| %>
     
                    <%= attachment_form.file_field :attachment %>
                    <%end%>
                  </div>
                </div>


                                      
                <div class="control-group">
                  <div class="paddingLR">
                    <button type="submit" name="sendTicket" class="btn">Create</button>
                    <span class="pull-right" id="error" style="color: #F33; padding-top:10px;"></span>
                  </div>
                </div>
              <% end %>
              <p></p> 
            </li>
          </ul>
        </li>
      </ul>
      <p class="navbar-text pull-right">
        <a href="/users/edit" class="btn btn-large btn-inverse ">Welcome <%= current_user.first_name %> </a>
        
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "btn btn-large btn-danger " %> 
      </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr style="margin-top:0px;">
		<footer class="pager" style="bottom:0px;">
		        <p>naren supportstack</p>
		</footer>

app/views/layouts/_header.html.erb
<div style="position: static;" class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a data-target=".subnav-collapse" data-toggle="collapse" class="btn btn-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="/" class="brand">SupportStack</a>
        <div class="nav-collapse subnav-collapse">
          <div class="pull-right">
            
            <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "navbar-search"}) do |f| %>

              <%= f.email_field :email, placeholder: "Email", class: "span3 input-block-level search-query" %>

              <%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: "span3 input-block-level search-query" %>

              <button class="btn btn-success btn-large" style="margin-top:-1px;" type="submit" name="login">login</button>
            
            <% end %>

          </div>
        </div><!-- /.nav-collapse -->
    </div>
  </div><!-- /navbar-inner -->
</div>

app/views/layouts/_staff_header.html.erb
<div class="navbar navbar-inverse" style="position: static;">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".subnav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/staff">SupportStack</a>
      <a class="brand marginTop" href="http://www.myflashlab.com/showcase/PHP_TICKET_SYSTEM/preview/"><i class="icon-home icon-white"></i></a>
      <div class="nav-collapse subnav-collapse">
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle " data-toggle="dropdown">Tickets <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="divider"></li>
              <li><%= link_to "Assigned tickets", staff_index_path(status_name: "assigned_tickets"), class: 'control-label' %></li>
              <li><%= link_to "Pending tickets", staff_index_path(status_name: "pending"), class: 'control-label' %></li>
              <li><%= link_to "Awaiting for user reply tickets", staff_index_path(status_name: "awaiting for users reply"), class: 'control-label' %></li>
              <li><%= link_to "Completed tickets", staff_index_path(status_name: "closed"), class: 'control-label' %></li>
            </li>
          </ul>
        </li>
      </ul>                    
      <p class="navbar-text pull-right">
        <a href="/users/edit" class="btn btn-large btn-inverse ">Welcome <%= current_user.first_name %> </a>
        
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "btn btn-large btn-danger " %> 
      </p>
    </div>
  </div>
</div>
</div>
           

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="robots" content="noindex">
<meta name="googlebot" content="noindex">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
<title>SupportStack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- <script type="text/javascript" src="home-page_files/ievfallback.js"></script> -->

<script type="text/javascript">
$(document).ready(function(){ $('#myModal').hide(); });
$('#myModal').modal({
    keyboard: false
  });
$('#myModal').modal('show');
</script>

<!-- <script src="client-profile_files/ievfallback.js"></script>
<link rel="stylesheet" type="text/css" href="client-profile_files/bootstrap.css">
<link rel="stylesheet" type="text/css" href="client-profile_files/bootstrap-responsive.css">
<link rel="stylesheet" type="text/css" href="client-profile_files/myCSS.css">
 -->
</head>

<body class="<%= controller.controller_name %>">
  <% if current_client %>          
    <%= render "layouts/client_header" %>
  <% elsif current_staff %>
    <%= render "layouts/staff_header" %>
  <% else %>
    <%= render "layouts/header" %>
  <% end %>

  <%= yield %>

  <%= render "layouts/footer" %>     
</body>
</html>